name: Sync From Gitea BONZ

on:
  workflow_dispatch:
    inputs:
      gitea_branch:
        description: 'Gitea Branch to Sync'
        required: true
        default: 'main'
      gitea_repo_url:
        description: 'Gitea Repository URL (without protocol)'
        required: true
        default: 'bonzuttner-git.up.railway.app/owlt/polaris-web.git'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Clone Gitea Branch
        run: |
          git clone --branch ${{ github.event.inputs.gitea_branch }} --single-branch https://oauth2:${{ secrets.GITEA_PAT }}@${{ github.event.inputs.gitea_repo_url }} gitea_repo

      - name: Sync Gitea Code to GitHub
        run: |
          rsync -av --exclude='.git' gitea_repo/ ./
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Sync from Gitea branch ${{ github.event.inputs.gitea_branch }}" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.OUR_PAT }}@github.com/${{ github.repository }}.git main
